FROM debian:buster-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        libgtk2.0-0 libx11-xcb1 libxtst6 libnss3 libasound2 libdbus-glib-1-2 xclip\
        tigervnc-standalone-server tigervnc-common psmisc flwm x11-utils \
        libjpeg-dev zlib1g-dev xfonts-intl-chinese xfonts-wqy


#ENV TYPE="" PASSWORD="" LOOP=""
ENV DISPLAY=:1
COPY . /app/

RUN apt-get update && \
    apt-get install -y --no-install-recommends --no-install-suggests \
        python3-pip python3-dev python3-tk build-essential \
        && python3 -m pip install setuptools wheel && python3 -m pip install -r /app/requirements.txt

CMD ["/app/docker/start.sh"]
